// src/app/features/home/components/features/features.component.ts
import {Component, OnInit} from '@angular/core';

const features: { image: string, headerText: string, bodyText: string, link: string, buttonColor: string }[] = [
  {
    image: 'app/assets/images/feature-1-image.png',
    headerText: 'Your data stays yours.',
    bodyText: 'Data privacy is one of the biggest concerns when we develop Pamaxie. The basic idea is that all data is stored in a private manner, including passwords, emails and other things.',
    link: '/DataPrivacy',
    buttonColor: '#DA5EBB'
  },
  {
    image: 'app/assets/images/feature-2-image.png',
    headerText: "Detects more than just images. (to be developed)",
    bodyText: 'Pamaxie is build ot detect more than just images and automatically analyse any kind of binary data sent to us. We plan to expand our neural network and analysers to recognize Videos, Malicious FIles and other things to basically allow any kind of bad software to be detected.',
    link: '/DataDetection',
    buttonColor: '#DA615E'
  },
  {
    image: 'app/assets/images/feature-3-image.png',
    headerText: 'Create a safe space to share experiences.',
    bodyText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est.',
    link: '/SafeSpace',
    buttonColor: '#DAB65E'
  },
  {
    image: 'app/assets/images/feature-4-image.png',
    headerText: 'Great speed and reliability.',
    bodyText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est.',
    link: '/Improvements',
    buttonColor: '#DA5EBB'
  },
  {
    image: 'app/assets/images/feature-5-image.png',
    headerText: 'Improve Community moderation efficiency.',
    bodyText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est.',
    link: '/Moderation',
    buttonColor: '#DA615E'
  },
  {
    image: 'app/assets/images/feature-6-image.png',
    headerText: 'Build to be open source.',
    bodyText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est.',
    link: '/OpenSource',
    buttonColor: '#DAB65E'
  }
];

@Component({
  selector: 'home-features',
  templateUrl: './features.component.html',
  styleUrls: ['./features.component.scss']
})
export class FeaturesComponent implements OnInit {
  features: { image: string, headerText: string, bodyText: string, link: string, buttonColor: string }[] = features

  constructor() {
  }

  ngOnInit(): void {
  }
}

<div class="flex flex-row flex-wrap m-9 bg-primary justify-evenly">
  <home-feature-card *ngFor="let feature of features" [image]="feature.image" [headerText]="feature.headerText"
                     [bodyText]="feature.bodyText" [link]="feature.link" [buttonColor]="feature.buttonColor"
                     class="flex-1-3 p-3">
  </home-feature-card>
</div>

// src/Sections/Home/Features.svelte
<script>
import Card from "../../Components/Card.svelte";
</script>

<div class="flex flex-row flex-wrap m-9 bg-primary justify-evenly">
    <Card
        image="../../img/feature-1-image.png"
        headerText="Your data stays yours."
        bodyText="Data privacy is one of the biggest concerns when we develop Pamaxie. The basic idea is that all data is stored in a private manner, including passwords, emails and other things."
        link="/DataPrivacy"
        buttonColor="#DA5EBB">
    </Card>
    <Card
        image="../../img/feature-2-image.png"
        headerText="Detects more than just images. (to be developed)"
        bodyText="Pamaxie is build ot detect more than just images and automatically analyse any kind of binary data sent to us. We plan to expand our neural network and analysers to recognize Videos, Malicious FIles and other things to basically allow any kind of bad software to be detected."
        link="/DataDetection"
        buttonColor="#DA615E">
    </Card>
    <Card
        image="../../img/feature-3-image.png"
        headerText="Create a safe space to share experiences."
        bodyText="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est."
        link="/SafeSpace"
        buttonColor="#DAB65E">
    </Card>
    <Card
        image="../../img/feature-4-image.png"
        headerText="Great speed and reliability."
        bodyText="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est."
        link="/Improvements"
        buttonColor="#DA5EBB">
    </Card>
    <Card
        image="../../img/feature-5-image.png"
        headerText="Improve Community moderation efficiency."
        bodyText="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est."
        link="/Moderation"
        buttonColor="#DA615E">
    </Card>
    <Card
        image="../../img/feature-6-image.png"
        headerText="Build to be open source."
        bodyText="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut purus turpis, posuere sed turpis in, faucibus feugiat nisi. Ut feugiat pellentesque nisl. Sed tellus ligula, pulvinar eu erat vitae, dictum aliquam eros. Fusce ornare molestie venenatis. Proin scelerisque urna nec lacus feugiat convallis. Morbi vulputate ultricies est."
        link="/OpenSource"
        buttonColor="#DAB65E">
    </Card>
</div>

<style>
</style>
