// src/app/features/home/components/footnote/footnote.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'home-footnote',
  templateUrl: './footnote.component.html',
  styleUrls: ['./footnote.component.scss']
})
export class FootnoteComponent implements OnInit {

  constructor() {
  }

  ngOnInit(): void {
  }

}

<div class="relative w-full bg-secondary" style="height: 24rem">
  <div class="flex flex-col absolute m-auto top-0 bottom-0 left-0 right-0 h-fit items-center"
       style="width: 53rem">
    <h1 class="contents text-4xl text-gray-primary text-center">And the best part: </h1>
    <h1 class="contents text-4xl text-center" style="color: #DAB65E">its free. </h1>
    <h1 class="contents text-4xl text-center" style="color: #DA615E">forever.</h1>
    <p class="m-3 text-2xl text-gray-primary text-center">We developed this solution to be free to use
      and easy to self host. We focus on high accessibility, making it easy to use even if you aren’t an
      experience developer. We offer documentation in multiple languages, that has been translated by our
      community. We also don’t collect any user data that isn’t required to run the service!</p>
    <button class="m-auto-4 p-2-4 left-0 right-0 rounded-full text-gray-primary bg-tertiary">Create
      Account
    </button>
  </div>
</div>

// src/Sections/Home/FootNote.svelte
<script>
</script>

<div class="relative w-full bg-secondary" style="height: 24rem;">
    <div class="flex flex-col absolute m-auto top-0 bottom-0 left-0 right-0 h-fit items-center" style="width: 53rem;">
        <h1 class="contents text-4xl text-gray-primary text-center">And the best part: </h1>
        <h1 class="contents text-4xl text-center" style="color: #DAB65E;">its free. </h1>
        <h1 class="contents text-4xl text-center" style="color: #DA615E;">forever.</h1>
        <p class="m-3 text-2xl text-gray-primary text-center">We developed this solution to be free to use and easy to self host. We focus on high accessibility, making it easy to use even if you aren’t an expierence developer. We offer documentation in multiple languages, that has been translated by our community. We also don’t collect any user data that isn’t required to run the service!</p>
        <button class="m-auto-4 p-2-4 left-0 right-0 rounded-full text-gray-primary bg-tertiary">Create Account</button>
    </div>
</div>

<style>
</style>
