// src/app/features/home/components/header/header.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'home-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  constructor() {
  }

  ngOnInit(): void {
  }
}

<div class="h-screen-12 flex flex-col">
  <div class="relative sm:h-2 md:h-2-5 h-1-2">
    <img src="app/assets/images/bg-header.png" alt="" class="absolute h-full w-full object-cover"/>
    <div class="absolute h-full w-full blur"></div>
    <div
      class="flex flex-col absolute m-auto top-0 bottom-0 left-0 right-0 h-fit md:w-53r items-center">
      <img src="app/assets/images/pamaxie-text-logo.png" alt="" class="md:h-32 h-24 object-contain"/>
      <h1 class="md:text-4xl text-xl text-center text-gray-primary">Content detection at your
        fingertips</h1>
      <p class="m-3 text-xs md:text-2xl text-gray-primary text-center">We are a content classification
        service that focuses on privacy and removing barriers. This helps applications developers and
        community moderators focus on more important things.</p>
    </div>
  </div>
  <div class="flex-1" style="background-color: #3A3A51">
    <div
      class="flex flex-col m-auto top-0 bottom-0 left-0 right-0 h-full md:w-53r items-center justify-center">
      <img src="app/assets/images/prototype-funding-image.png" alt=""
           class="h-1-5 h-max-9r w-full object-contain"/>
      <h1 class="md:text-4xl text-xl text-gray-primary">Funded via Prototypefund</h1>
      <p class="m-3 md:text-2xl text-xs text-gray-primary text-center">
        We are officially part of Prototypefund's 12th round, we are happy to develop together with the
        open knowledge foundation Germany.
        <br/>
        Wanna know more?
      </p>
      <button
        class="p-2-4 left-0 right-0 bg-tertiary rounded-full border-none text-gray-primary">Learn
        More
      </button>
    </div>
  </div>
</div>

// src/Sections/Home/Header.svelte
<script>
</script>

<div id="header" class="h-screen-12 flex flex-col">
    <div class="relative sm:h-2 md:h-2-5 h-1-2">
        <img src="../../img/bg-header.png" alt="HeaderImage" class="absolute h-full w-full object-cover"/>
        <div class="absolute h-full w-full blur"></div>
        <div class="flex flex-col absolute m-auto top-0 bottom-0 left-0 right-0 h-fit md:w-53r items-center">
            <img src="../../img/pamaxie-text-logo.png" alt="Title" class="md:h-32 h-24 object-contain"/>
            <h1 class="md:text-4xl text-xl text-center text-gray-primary">Content detection at your fingertips</h1>
            <p class="m-3 text-xs md:text-2xl text-gray-primary text-center">We are a content classification service that focuses on privacy and removing barriers. This helps applications developers and community moderators focus on more important things.</p>
        </div>
    </div> <!--sm:text-4xl xl:text-5xl-->
    <div class="flex-1" style="background-color: #3A3A51">
        <div class="flex flex-col m-auto top-0 bottom-0 left-0 right-0 h-full md:w-53r items-center justify-center">
            <img src="../../img/prototype-funding-image.png" alt="PrototypeImage" class="h-1-5 h-max-9r w-full object-contain"/>
            <h1 class="md:text-4xl text-xl text-gray-primary">Funded via Prototypefund</h1>
            <p class="m-3 md:text-2xl text-xs text-gray-primary text-center">
                We are officially part of Prototypefund's 12th round, we are happy to develop together with the open knowledge foundation Germany.
                <br>
                Wanna know more?
            </p>
            <button class="p-2-4 left-0 right-0 bg-tertiary rounded-full border-none text-gray-primary">Learn More</button>
        </div>
    </div>
</div>

<style>
</style>
