// src/Components/FeaturePage.svelte
<script>
    export let headerText;
    export let bodyText;
    export let image;
</script>

<div class="flex flex-row h-screen-24 bg-secondary">
    <div class="flex-1 m-8">
        <img src="../../img/pamaxie-text-logo.png" alt="Title" class="h-32 object-contain"/>
        <h1 class="m-2-8 text-4xl text-gray-primary">{headerText}</h1>
        <p class="m-2-8 text-2 text-gray-primary">
            <slot></slot>
        </p>
    </div>
    <img src="{image}" alt="image" class="flex-2-5 h-full object-cover overflow-hidden">
</div>

<style>

</style>

// src/app/features/home/components/feature-page/feature-page.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'home-feature-page',
  templateUrl: './feature-page.component.html',
  styleUrls: ['./feature-page.component.scss']
})
export class FeaturePageComponent implements OnInit {
  logo: string = 'app/assets/images/pamaxie-text-logo.png';
  @Input() image: string = '';
  @Input() headerText: string = '';
  @Input() innerText: string[] | undefined;

  constructor() {
  }

  ngOnInit(): void {
  }
}

<div class="flex flex-row h-screen-24 bg-secondary">
  <div class="flex-1 m-8">
    <img [src]="logo" alt="" class="h-32 object-contain"/>
    <h1 class="m-2-8 text-4xl text-gray-primary">{{headerText}}</h1>
    <p class="m-2-8 text-2 text-gray-primary">
      <ng-container *ngFor="let text of innerText; let i = index">
        <ng-container *ngIf="i > 0">
          <br/>
        </ng-container>
        {{text}}
      </ng-container>
    </p>
  </div>
  <img [src]="image" alt="" class="flex-2-5 h-full object-cover overflow-hidden bg-white"/>
</div>
