// src/Components/Dropdown.svelte
<script>
    export let id;

    //Clicking dropdown button will toggle display and prevent outside click from triggering
    function dropdown(e) {
        document.getElementById(id + "Content").classList.toggle('hidden');
        e.stopPropagation();
    }

    //Closes the menu if outside clicks are triggered
    window.onclick = function(e) {
        if (!e.target.matches(id + "Button")) {
            let dropdown = document.getElementById(id + "Content")
                if (!dropdown.classList.contains('hidden')) {
                    dropdown.classList.add('hidden');
                }
        }
    }
</script>

<div class="relative inline-block">
    <button id="{id}Button" on:click={dropdown} class="flex items-center justify-between w-full py-2 pl-3 pr-4 font-medium text-gray-primary border-b border-gray-100 md:p-0 md:w-auto md:border-0 focus:outline-none">
        <slot name="InnerHTML"></slot>
    </button>
    <div id="{id}Content" class="absolute w-40 bg-secondary rounded text-1 text-gray-primary list-none shadow z-50 hidden">
        <slot name="Content"></slot>
    </div>
</div>

<style>
</style>

// src/app/core/components/dropdown/dropdown.component.ts
import {Component, HostListener, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-dropdown',
  templateUrl: './dropdown.component.html',
  styleUrls: ['./dropdown.component.scss']
})
export class DropdownComponent implements OnInit {
  @Input() id: string = '';
  @Input() content: string = '';
  idButton: string = '';
  idContent: string = '';

  constructor() {
  }

  ngOnInit(): void {
    this.idButton = this.id + 'Button';
    this.idContent = this.id + 'Content';
  }

  dropdown(e: any) {
    let element = document.getElementById(this.idContent);
    if (element)
    {
      element.classList.toggle('hidden');
    }
    e.stopPropagation();
  }

  @HostListener('window:click', ['$event'])
  onDocumentClick(e: any) {
    if (e.target)
    {
      if (!e.target.matches(this.idButton)) {
        let dropdown = document.getElementById(this.idContent)
        if (dropdown)
        {
          if (!dropdown.classList.contains('hidden')) {
            dropdown.classList.add('hidden');
          }
        }
      }
    }
  }
}

<div class="relative inline-block">
  <button [id]=idButton (click)="dropdown($event)"
          class="flex items-center justify-between w-full py-2 pl-3 pr-4 font-medium text-gray-primary border-b border-gray-100 md:p-0 md:w-auto md:border-0 focus:outline-none">
    <ng-content select="[buttonText]"></ng-content>
  </button>
  <div [id]=idContent
       class="absolute w-40 bg-secondary rounded text-1 text-gray-primary list-none shadow z-50 hidden">
    <ng-content select="[content]"></ng-content>
  </div>
</div>
