// src/app/features/error/components/error-page/error-page.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'error-page',
  templateUrl: './error-page.component.html',
  styleUrls: ['./error-page.component.scss']
})
export class ErrorPageComponent implements OnInit {
  logo: any = 'app/assets/images/pamaxie-text-logo.png';
  @Input() image: string = '';
  @Input() headerText: string = '';
  @Input() bodyText: string = '';
  @Input() buttonInfo: { text: string; path: string; }[] | undefined;

  constructor() {
  }

  ngOnInit(): void {
  }
}

<div class="flex flex-row h-screen-24 bg-secondary">
  <div class="flex flex-col flex-1 justify-center items-center m-8">
    <img [src]="logo" alt="" class="h-32 object-contain"/>
    <h1 class="m-2-8 text-4xl text-gray-primary font-bold">{{headerText}}</h1>
    <p class="m-2-8 text-2 text-gray-primary text-center" style="max-width: 830px">
      {{bodyText}}
    </p>
    <a *ngFor="let info of buttonInfo"
       class="block px-4 py-2 bg-tertiary rounded-full text-gray-primary hover:bg-primary" style="margin: 3px"
       [routerLink]="info.path" routerLinkActive="active">
      {{info.text}}
    </a>
  </div>
  <img [src]="image" alt="" class="flex-2-5 h-full object-cover overflow-hidden bg-tertiary"/>
</div>

// src/Components/ErrorPage.svelte
<script>
    export let headerText;
    export let image;
    export let buttons;
</script>

<div class="flex flex-row h-screen-24 bg-secondary">
    <div class="flex-1 m-8">
        <img src="../../img/pamaxie-text-logo.png" alt="Title" class="h-32 object-contain"/>
        <h1 class="m-2-8 text-4xl text-gray-primary">{headerText}</h1>
        <p class="m-2-8 text-2 text-gray-primary">
            <slot></slot>
        </p>
    </div>
    <img src="{image}" alt="image" class="flex-2-5 h-full object-cover overflow-hidden">
</div>

<style>

</style>
